# Generated by Django 4.2.3 on 2023-07-31 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animes', '0002_alter_anime_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.IntegerField(),
        ),
    ]
